version: '3.8'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      - POSTGRES_DB=boapp_db
      - DATABASE_HOST=127.0.01
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - /home/pachiracledev/postgres-gongian:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
      - database_volume:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  database_volume:
